version: 0.2
phases:
  pre_build:
    commands:
      - ls      
  build:
    commands:
      - echo Build started on `date`
      - make docker
      #- make lambda
      #- make eb
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
  # move all files to the output
    - '**/*'