version: 0.2
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - sudo apt-get install zip gzip tar -y
      - pip3 install --upgrade pip
      - pip install taskcat==0.7.27      
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - chmod +x ci/setup-validate.sh
      - /bin/bash ci/setup-validate.sh
      - export dirname=${PWD##*/}
      - echo Directory name $dirname
      - cd ..
      - mv $dirname $PROJECTNAME
      - echo Configuring aws cli...
      - aws configure set default.region us-east-1
  build:
    commands:
      - echo Entered the build phase...
      - taskcat -c $PROJECTNAME/ci/taskcat.yml
      - echo Zipping and uploading report to $ARTIFACT_BUCKET S3 bucket
      - zip -r taskcat_report.zip taskcat_outputs
      - aws s3 cp taskcat_report.zip s3://$ARTIFACT_BUCKET/taskcat_reports/$CODEBUILD_BUILD_ID.zip
      - |
        if $(grep -Fq "CREATE_FAILED" taskcat_outputs/index.html)
        then
          echo Quickstart FAILED!
          exit 1
        else
          echo Quickstart Passed!
          exit 0
        fi
